/**
 * Proves the browser's filter chain has the same magnitude response as the
 * SciPy one, for every preset, at both common sample rates.
 *
 * This is the claim the README makes and the reason the two front ends can be
 * called the same equaliser. Reference values come from
 * tests/golden/response.json (generated by tools/gen_golden.py from
 * scipy.signal.sosfreqz); tests/test_parity.py fails first if they go stale.
 *
 * The band table is imported here in Node and passed into the page as plain
 * data. The page therefore fetches nothing — what is under test is Web Audio's
 * BiquadFilterNode, not module loading, and keeping the static server out of
 * the hot path makes the suite hermetic.
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { expect, test } from '@playwright/test';

import { BANDS, PRESET_NAMES } from '../../web/spec.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const GOLDEN = JSON.parse(
  readFileSync(join(HERE, '..', 'golden', 'response.json'), 'utf8'),
);

/**
 * Web Audio's getFrequencyResponse returns float32, so the floor here is
 * float32 epsilon on a ~10 dB value, not an algorithmic tolerance. Anything
 * above this means the filters genuinely differ.
 */
const TOLERANCE_DB = 5e-3;

/** Builds the cascade in the page and reads its response back out. */
async function measureResponse(page, { bands, gains, fs, freqs }) {
  return page.evaluate(
    ({ bands, gains, fs, freqs }) => {
      // An OfflineAudioContext is enough: getFrequencyResponse needs the nodes
      // to exist, not the graph to run. It also avoids the live-AudioContext
      // limit a browser enforces per page.
      const ctx = new OfflineAudioContext(1, 1, fs);
      const nodes = bands.map((band) => {
        const node = ctx.createBiquadFilter();
        node.type = band.kind;
        node.frequency.value = band.f0;
        node.Q.value = band.q;
        node.gain.value = gains[band.key];
        return node;
      });

      const probe = new Float32Array(freqs);
      const mag = new Float32Array(freqs.length);
      const phase = new Float32Array(freqs.length);
      const total = new Array(freqs.length).fill(0);

      // Sections cascade, so magnitudes multiply — i.e. dB add.
      for (const node of nodes) {
        node.getFrequencyResponse(probe, mag, phase);
        for (let i = 0; i < freqs.length; i++) {
          total[i] += 20 * Math.log10(Math.max(mag[i], 1e-12));
        }
      }
      return total;
    },
    { bands, gains, fs, freqs },
  );
}

test.describe('Web Audio matches the SciPy cascade', () => {
  for (const testCase of GOLDEN.cases) {
    test(`${testCase.preset} @ ${testCase.fs} Hz`, async ({ page }) => {
      await page.goto('about:blank');

      const measured = await measureResponse(page, {
        bands: BANDS,
        gains: testCase.gains,
        fs: testCase.fs,
        freqs: GOLDEN.freqs,
      });

      expect(measured).toHaveLength(testCase.db.length);

      let worst = 0;
      let worstAt = 0;
      for (let i = 0; i < measured.length; i++) {
        const diff = Math.abs(measured[i] - testCase.db[i]);
        if (diff > worst) {
          worst = diff;
          worstAt = GOLDEN.freqs[i];
        }
      }

      expect(
        worst,
        `largest divergence from SciPy was ${worst.toExponential(2)} dB `
        + `at ${worstAt.toFixed(1)} Hz`,
      ).toBeLessThan(TOLERANCE_DB);
    });
  }
});

test.describe('the deployed page', () => {
  test('boots and exposes the generated spec', async ({ page }) => {
    const errors = [];
    page.on('pageerror', (err) => errors.push(err.message));
    page.on('console', (msg) => {
      if (msg.type() === 'error') errors.push(msg.text());
    });

    await page.goto('/index.html');
    await expect(page.locator('#eqCanvas')).toBeVisible();

    // The band reference table is built from spec.js at runtime; if the
    // generated module failed to load, these rows would be missing.
    await expect(page.locator('#bandTableBody tr')).toHaveCount(BANDS.length);

    // Every preset should be selectable.
    await expect(page.locator('#preset option')).toHaveCount(PRESET_NAMES.length);

    // The response plot must describe itself for assistive technology.
    await expect(page.locator('#eqCanvas')).toHaveAttribute(
      'aria-label', /pass-through/,
    );

    expect(errors, `page reported: ${errors.join(' | ')}`).toEqual([]);
  });
});
