/**
 * The browser build's ported analysis, checked against SciPy's output.
 *
 * Reference values come from tests/golden/*.json, generated by
 * tools/gen_golden.py. If the Python implementation changes, those files go
 * stale and tests/test_golden.py fails first — so these two suites cannot
 * drift apart silently.
 *
 * Run: node --test tests/js/
 */

import { strict as assert } from 'node:assert';
import test from 'node:test';

import {
  BANDS, BAND_KEYS, GAIN_MAX_DB, GAIN_MIN_DB, HEADROOM_PEAK, PRESETS,
  PRESET_NAMES, PRESET_NOTES, clampGain, encodeWav, flatGains, gainStaging,
  getPreset, octaveSmooth, peakOf, spectrum, toMono, waveformEnvelope,
} from '../../web/dsp.js';

import { buildSignal, golden } from './golden.mjs';

// --------------------------------------------------------------------------
// Welch spectrum
// --------------------------------------------------------------------------

for (const [label, file] of [
  ['raw', 'spectrum_raw.json'],
  ['1/12-octave smoothed', 'spectrum_smoothed.json'],
]) {
  test(`spectrum (${label}) matches SciPy`, () => {
    const g = golden(file);
    const x = buildSignal(g.signal);
    const got = spectrum(x, g.signal.fs, { smoothFraction: g.smooth_fraction });

    assert.equal(got.freqs.length, g.bins, 'bin count differs from SciPy');
    assert.equal(2 * (got.freqs.length - 1), g.nperseg, 'segment length differs');

    let worstDb = 0;
    let worstHz = 0;
    for (const probe of g.probes) {
      assert.ok(
        Math.abs(got.freqs[probe.bin] - probe.freq) < 1e-9,
        `bin ${probe.bin} sits at a different frequency`,
      );
      worstHz = Math.max(worstHz, Math.abs(got.freqs[probe.bin] - probe.freq));
      worstDb = Math.max(worstDb, Math.abs(got.db[probe.bin] - probe.db));
    }
    // Float64 throughout on both sides; anything above this is a real
    // algorithmic difference, not rounding.
    assert.ok(worstDb < 1e-6, `worst |difference| was ${worstDb} dB`);
  });
}

test('spectrum detrends each segment, so a DC offset does not dominate', () => {
  const fs = 8192;
  const n = fs * 2;
  const withDc = new Float64Array(n);
  const withoutDc = new Float64Array(n);
  for (let i = 0; i < n; i++) {
    const tone = 0.5 * Math.sin((2 * Math.PI * 1000 * i) / fs);
    withDc[i] = tone + 0.9;
    withoutDc[i] = tone;
  }
  const a = spectrum(withDc, fs, { smoothFraction: 0 });
  const b = spectrum(withoutDc, fs, { smoothFraction: 0 });

  const at1k = Math.round((1000 / fs) * 2 * (a.freqs.length - 1));
  assert.ok(Math.abs(a.db[at1k] - b.db[at1k]) < 1e-9, 'the tone bin moved');
});

test('spectrum segment length is a power of two and fits the signal', () => {
  for (const n of [500, 5000, 50000]) {
    const { freqs } = spectrum(new Float64Array(n), 44100);
    const nperseg = 2 * (freqs.length - 1);
    assert.equal(nperseg & (nperseg - 1), 0, `nperseg ${nperseg} is not a power of two`);
    assert.ok(nperseg <= n, `nperseg ${nperseg} exceeds the signal length ${n}`);
  }
});

test('spectrum survives a signal shorter than one segment', () => {
  const { freqs, db } = spectrum(new Float64Array(7), 44100);
  assert.ok(freqs.length >= 1 && db.length === freqs.length);
  assert.ok(db.every(Number.isFinite));
});

// --------------------------------------------------------------------------
// Smoothing
// --------------------------------------------------------------------------

test('octaveSmooth leaves a flat spectrum flat', () => {
  const freqs = new Float64Array(2048);
  const power = new Float64Array(2048).fill(3.0);
  for (let i = 0; i < freqs.length; i++) freqs[i] = 1 + (i * 20000) / 2048;

  const out = octaveSmooth(freqs, power, 12.0);
  for (const v of out) assert.ok(Math.abs(v - 3.0) < 1e-12);
});

test('octaveSmooth is a no-op when disabled', () => {
  const freqs = Float64Array.from({ length: 64 }, (_, i) => i + 1);
  const power = Float64Array.from({ length: 64 }, (_, i) => (i * 37) % 11);
  assert.deepEqual(Array.from(octaveSmooth(freqs, power, 0)), Array.from(power));
});

// --------------------------------------------------------------------------
// Waveform envelope
// --------------------------------------------------------------------------

test('waveformEnvelope matches the Python envelope', () => {
  const g = golden('envelope.json');
  const x = buildSignal(g.signal);
  const env = waveformEnvelope(x, g.target_points);

  assert.equal(env.min.length, g.size);
  let worst = 0;
  for (const probe of g.probes) {
    worst = Math.max(
      worst,
      Math.abs(env.min[probe.i] - probe.min),
      Math.abs(env.max[probe.i] - probe.max),
    );
  }
  assert.ok(worst < 1e-9, `worst |difference| was ${worst}`);
});

test('waveformEnvelope brackets the signal and passes short input through', () => {
  const x = Float64Array.from({ length: 20000 }, (_, i) =>
    Math.sin((2 * Math.PI * 5 * i) / 20000));
  const env = waveformEnvelope(x, 200);
  assert.equal(env.min.length, 200);
  for (let i = 0; i < 200; i++) assert.ok(env.min[i] <= env.max[i]);

  const tiny = Float64Array.from([0.1, -0.2, 0.3]);
  const passed = waveformEnvelope(tiny, 2000);
  assert.deepEqual(Array.from(passed.min), Array.from(tiny));
});

// --------------------------------------------------------------------------
// Gain staging
// --------------------------------------------------------------------------

test('gainStaging matches the Python gain staging exactly', () => {
  const g = golden('gain_staging.json');
  assert.equal(HEADROOM_PEAK, g.headroom_peak, 'headroom constant diverged');

  for (const c of g.cases) {
    const got = gainStaging(c.peak);
    assert.equal(got.clipped, c.clipped, `clipped flag differs at peak ${c.peak}`);
    assert.ok(Math.abs(got.scale - c.scale) < 1e-12, `scale differs at peak ${c.peak}`);
    assert.ok(
      Math.abs(got.appliedGainDb - c.applied_gain_db) < 1e-9,
      `dB differs at peak ${c.peak}`,
    );
  }
});

test('gainStaging only ever attenuates', () => {
  for (const peak of [0, 0.1, 0.5, 0.9, 1.0, 5.0]) {
    assert.ok(gainStaging(peak).scale <= 1.0);
    assert.ok(gainStaging(peak).appliedGainDb <= 0);
  }
});

test('peakOf scans every channel', () => {
  const left = Float32Array.from([0.1, -0.2]);
  const right = Float32Array.from([0.05, -0.77]);
  assert.ok(Math.abs(peakOf([left, right]) - 0.77) < 1e-7);
});

test('toMono averages channels', () => {
  const mono = toMono([Float32Array.from([1, 1]), Float32Array.from([0, 0])]);
  assert.ok(Math.abs(mono[0] - 0.5) < 1e-12);
});

// --------------------------------------------------------------------------
// Spec-derived values
// --------------------------------------------------------------------------

test('the band table is well formed', () => {
  assert.equal(BANDS.length, 7);
  assert.equal(BANDS[0].kind, 'lowshelf');
  assert.equal(BANDS[BANDS.length - 1].kind, 'highshelf');
  for (const b of BANDS.slice(1, -1)) assert.equal(b.kind, 'peaking');

  const f0s = BANDS.map((b) => b.f0);
  assert.deepEqual(f0s, [...f0s].sort((a, z) => a - z), 'centres are out of order');
  for (const b of BANDS) assert.ok(b.q > 0 && Number.isFinite(b.q));
});

test('presets cover every band and stay inside the slider range', () => {
  for (const name of PRESET_NAMES) {
    const gains = getPreset(name);
    assert.deepEqual(Object.keys(gains).sort(), [...BAND_KEYS].sort());
    for (const [key, value] of Object.entries(gains)) {
      assert.ok(
        value >= GAIN_MIN_DB && value <= GAIN_MAX_DB,
        `${name}.${key} = ${value} is out of range`,
      );
    }
    assert.ok(PRESET_NOTES[name], `${name} has no note`);
  }
});

test('the default preset is flat', () => {
  assert.ok(Object.values(getPreset(PRESET_NAMES[0])).every((v) => v === 0));
});

test('getPreset returns a copy', () => {
  const a = getPreset('Bass Boost');
  a.bass = 99;
  assert.notEqual(getPreset('Bass Boost').bass, 99);
  assert.notEqual(PRESETS['Bass Boost'].bass, 99);
});

test('flatGains is all zeroes for every band', () => {
  const flat = flatGains();
  assert.deepEqual(Object.keys(flat).sort(), [...BAND_KEYS].sort());
  assert.ok(Object.values(flat).every((v) => v === 0));
});

test('clampGain respects the slider range', () => {
  assert.equal(clampGain(99), GAIN_MAX_DB);
  assert.equal(clampGain(-99), GAIN_MIN_DB);
  assert.equal(clampGain(3.5), 3.5);
});

// --------------------------------------------------------------------------
// WAV encoding
// --------------------------------------------------------------------------

test('encodeWav writes a valid 16-bit PCM header', async () => {
  const frames = 1000;
  const left = Float32Array.from({ length: frames }, (_, i) =>
    Math.sin((2 * Math.PI * 440 * i) / 44100));
  const right = Float32Array.from(left, (v) => v * 0.5);

  const blob = encodeWav([left, right], 44100);
  const view = new DataView(await blob.slice(0, 44).arrayBuffer());
  const text = (a, b) => String.fromCharCode(
    ...new Uint8Array(view.buffer.slice(a, b)));

  assert.equal(text(0, 4), 'RIFF');
  assert.equal(text(8, 12), 'WAVE');
  assert.equal(text(36, 40), 'data');
  assert.equal(view.getUint16(20, true), 1, 'not PCM');
  assert.equal(view.getUint16(22, true), 2, 'channel count');
  assert.equal(view.getUint32(24, true), 44100, 'sample rate');
  assert.equal(view.getUint16(34, true), 16, 'bit depth');

  const declared = view.getUint32(40, true);
  assert.equal(declared, frames * 2 * 2, 'declared data size');
  assert.equal(blob.size - 44, declared, 'declared size does not match the payload');
});

test('encodeWav saturates instead of wrapping', async () => {
  const hot = Float32Array.from([2.0, -2.0, 0.0]);
  const blob = encodeWav([hot], 8000);
  const view = new DataView(await blob.slice(44).arrayBuffer());

  assert.equal(view.getInt16(0, true), 32767, 'positive overflow wrapped');
  assert.equal(view.getInt16(2, true), -32768, 'negative overflow wrapped');
  assert.equal(view.getInt16(4, true), 0);
});
